### ISSUE TITLE
[Issue]Player plates seem to break iron doors On server.

### ISSUE THREAD

**Issue by Daihok41** [nanite/Player-Plates#18]
### Mod version

1.1.4-build.7 1.18.2

### Forge mod loader version

40.0.45

### Repeatable?

- [X] Yes

### Link to log files

No log shows it

### Steps to reproduce the issue

Log into server place iron doors and place the player obsidian plates sometime they break doors sometimes they dont

### Description of the issue you are having

Log into server place iron doors and place the player obsidian plates sometime they break doors sometimes they dont I am using a large modpack I have been trying to find which mod is conflicting with this one but cant, It doesnt do it if only few mods are installed but in large pack on server always breaks my iron doors. Half the door will open and half wont ect.

### Information

- [X] I have provided as much information as possible

**Comment by Daihok41** [comment]
I have found this is not just pplayer plates it seems its modded plates and buttons in general so im not sure which mod is conflicting

**Comment by Gaz492** [comment]
I tested my mod on the forge version you mentioned, and I'm unable to repeat the issue you are experiencing.
I suggest contacting the modpack author.
