### ISSUE TITLE
[1.21] Player plates incompatibility with Neo Forge 1.21

### ISSUE THREAD

**Issue by Periam** [nanite/Player-Plates#22]
### Minecraft Version

1.21

### Modloader

Neoforge 21.0.14

### Mod version

MC 1.21

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/user-attachments/files/15875437/latest.log)

### Steps to reproduce the issue

Install the mod and start the game.

### Description of the issue you are having

After starting the game the mod is flagged as incompatibility for new neo forge version.

![Screenshot 2024-06-17 152953](https://github.com/nanite/Player-Plates/assets/13920185/f138e041-3148-4dc5-93d3-39003ba6bb8f)

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
Fixed version should be on curseforge in a few minutes
